#!/usr/bin/env python3
"""Bake the 3D viewer's assembly + STL meshes into classic JavaScript data files.

Why: some hosts (e.g. anonymous.4open.science) serve pages inside a CSP sandbox
without allow-same-origin, so fetch()/XHR to the site's own files fails. Plain
<script src> loads still work, so the viewer reads its data from these files.

Inputs : media/models/assembly.json, and the binary STL files it references.
Outputs: media/models/assembly-data.js  (window.MARBLE_ASSEMBLY = {...})
         media/models/meshes-<k>.js     (window.MARBLE_MESH_CHUNKS.push({...}))
         and updates MODEL_DATA_VERSION in media/js/viewer3d.js (cache busting).

Mesh encoding (per unique geometry, identical meshes are stored once):
  vertices welded on their quantized position, stored as little-endian Uint16
  triples relative to the mesh bounding box (x = min + q * step); triangles
  stored as little-endian Uint16 or Uint32 indices (degenerate ones dropped).
  Normals are not stored: the viewer expands to a non-indexed geometry and
  calls computeVertexNormals(), which gives the same flat shading as before.

Usage: python3 tools/bake_model.py        (run from anywhere; stdlib only)
"""
import base64, glob, hashlib, json, os, re, struct, sys
from array import array

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODELS = os.path.join(ROOT, "media", "models")
VIEWER_JS = os.path.join(ROOT, "media", "js", "viewer3d.js")
CHUNK_TARGET = 1_500_000  # approx. bytes of JS per mesh chunk file
QMAX = 65535

if sys.byteorder != "little":
    sys.exit("bake_model.py expects a little-endian host")


def read_stl(path):
    data = open(path, "rb").read()
    n = struct.unpack_from("<I", data, 80)[0] if len(data) >= 84 else 0
    if len(data) != 84 + 50 * n:
        return read_ascii_stl(data)
    tris = []
    for i in range(n):
        tris.append(struct.unpack_from("<9f", data, 84 + 50 * i + 12))
    return tris


def read_ascii_stl(data):
    vals = [float(v) for v in re.findall(rb"vertex\s+(\S+)\s+(\S+)\s+(\S+)", data) for v in v]
    if len(vals) % 9:
        raise ValueError("malformed ASCII STL")
    return [tuple(vals[i:i + 9]) for i in range(0, len(vals), 9)]


def encode_mesh(tris):
    xs = [t[j] for t in tris for j in (0, 3, 6)]
    ys = [t[j] for t in tris for j in (1, 4, 7)]
    zs = [t[j] for t in tris for j in (2, 5, 8)]
    mn = [min(xs), min(ys), min(zs)]
    mx = [max(xs), max(ys), max(zs)]
    step = [(mx[a] - mn[a]) / QMAX if mx[a] > mn[a] else 0.0 for a in range(3)]
    # float32 round-trip so the stored numbers are short and exact on decode
    step = [struct.unpack("<f", struct.pack("<f", s))[0] for s in step]
    mn = [struct.unpack("<f", struct.pack("<f", m))[0] for m in mn]

    def q(v, a):
        if step[a] == 0.0:
            return 0
        return max(0, min(QMAX, int(round((v - mn[a]) / step[a]))))

    lookup, verts, idx = {}, array("H"), []
    for t in tris:
        tri = []
        for k in range(3):
            key = (q(t[3 * k], 0), q(t[3 * k + 1], 1), q(t[3 * k + 2], 2))
            i = lookup.get(key)
            if i is None:
                i = lookup[key] = len(lookup)
                verts.extend(key)
            tri.append(i)
        if tri[0] != tri[1] and tri[1] != tri[2] and tri[0] != tri[2]:
            idx.extend(tri)
    wide = len(lookup) > 65535
    ind = array("I" if wide else "H", idx)
    return {
        "vc": len(lookup),
        "ic": len(idx),
        "iw": 4 if wide else 2,
        "min": [round(m, 6) for m in mn],
        "step": step,
        "p": base64.b64encode(verts.tobytes()).decode("ascii"),
        "i": base64.b64encode(ind.tobytes()).decode("ascii"),
    }


def compact(o):
    if isinstance(o, float):
        r = round(o, 9)
        return 0 if r == 0 else r
    if isinstance(o, list):
        return [compact(v) for v in o]
    if isinstance(o, dict):
        return {k: compact(v) for k, v in o.items()}
    return o


def main():
    assembly = json.load(open(os.path.join(MODELS, "assembly.json")))
    unique = {}  # geometry hash -> [names, tris]
    for name, rel in assembly["mesh_files"].items():
        tris = read_stl(os.path.join(ROOT, rel))
        h = hashlib.sha1(array("f", [v for t in tris for v in t]).tobytes()).hexdigest()
        unique.setdefault(h, [[], tris])[0].append(name)

    chunks, cur, cur_size = [], [], 0
    for names, tris in unique.values():
        rec = encode_mesh(tris)
        rec["names"] = names
        size = len(rec["p"]) + len(rec["i"])
        if cur and cur_size + size > CHUNK_TARGET:
            chunks.append(cur)
            cur, cur_size = [], 0
        cur.append(rec)
        cur_size += size
    if cur:
        chunks.append(cur)

    for old in glob.glob(os.path.join(MODELS, "meshes-*.js")):
        os.remove(old)

    header = "/* Generated by tools/bake_model.py - do not edit. */\n"
    chunk_urls, total = [], 0
    for k, recs in enumerate(chunks):
        body = (header + "(window.MARBLE_MESH_CHUNKS = window.MARBLE_MESH_CHUNKS || []).push("
                + json.dumps({"meshes": recs}, separators=(",", ":")) + ");\n")
        fname = "meshes-%d.js" % k
        open(os.path.join(MODELS, fname), "w").write(body)
        digest = hashlib.sha1(body.encode()).hexdigest()[:10]
        chunk_urls.append("media/models/%s?v=%s" % (fname, digest))
        total += len(body)
        print("%-12s %8d bytes, %d meshes" % (fname, len(body), len(recs)))

    data = {k: compact(v) for k, v in assembly.items() if k != "mesh_files"}
    data["mesh_chunks"] = chunk_urls
    data["mesh_count"] = sum(len(n) for n, _ in unique.values())
    body = (header + "window.MARBLE_ASSEMBLY = "
            + json.dumps(data, separators=(",", ":")) + ";\n")
    open(os.path.join(MODELS, "assembly-data.js"), "w").write(body)
    total += len(body)
    version = hashlib.sha1(body.encode()).hexdigest()[:10]
    print("%-12s %8d bytes" % ("assembly-data.js", len(body)))
    print("total        %8d bytes; %d mesh names, %d unique geometries"
          % (total, data["mesh_count"], len(unique)))

    src = open(VIEWER_JS).read()
    new, n = re.subn(r'(const MODEL_DATA_VERSION = ")[^"]*(";)', r"\g<1>%s\g<2>" % version, src)
    if n != 1:
        sys.exit("could not find MODEL_DATA_VERSION in media/js/viewer3d.js")
    if new != src:
        open(VIEWER_JS, "w").write(new)
    print("MODEL_DATA_VERSION =", version)


if __name__ == "__main__":
    main()
